export interface AgentData {
  id?: string;
  name: string;
  emoji: string;
  role: string;
  description: string;
  mission: string;
  model: string;
  modelPrice?: string;
  department: string;
}

export const AGENTS_DATA: Record<string, AgentData> = {
  // Direction (4 agents)
  "ceo-strategist": {
    name: "CEO Stratégiste",
    emoji: "👔",
    role: "Directeur Stratégique",
    description: "Définit la vision marketing globale et les objectifs business",
    mission: "Aligner la stratégie marketing avec les objectifs de croissance",
    model: "claude-3-5-sonnet",
    department: "direction",
  },
  "cmo-chief": {
    name: "CMO Principal",
    emoji: "🎯",
    role: "Chief Marketing Officer",
    description: "Supervise toutes les initiatives marketing et optimise le ROI",
    mission: "Maximiser l'impact et le retour sur investissement marketing",
    model: "gpt-4",
    department: "direction",
  },
  "growth-hacker": {
    name: "Growth Hacker",
    emoji: "🚀",
    role: "Spécialiste Croissance",
    description: "Identifie et teste des leviers de croissance rapide",
    mission: "Trouver des hacks de croissance scalables",
    model: "gemini-2.0-flash-exp",
    department: "direction",
  },
  "data-analyst-chief": {
    name: "Analyste en Chef",
    emoji: "📊",
    role: "Directeur Analytique",
    description: "Analyse les données et génère des insights stratégiques",
    mission: "Transformer les données en décisions actionnables",
    model: "gpt-4",
    department: "direction",
  },

  // Prospection (8 agents)
  "lead-scraper": {
    name: "Lead Scraper",
    emoji: "🔍",
    role: "Extracteur de Prospects",
    description: "Trouve et qualifie des prospects sur le web",
    mission: "Identifier des leads qualifiés automatiquement",
    model: "gemini-2.0-flash-exp",
    department: "prospection",
  },
  "email-finder": {
    name: "Email Finder",
    emoji: "📧",
    role: "Trouveur d'Emails",
    description: "Découvre les emails professionnels des prospects",
    mission: "Construire des listes d'emails vérifiées",
    model: "llama-3.3-70b",
    department: "prospection",
  },
  "linkedin-hunter": {
    name: "LinkedIn Hunter",
    emoji: "💼",
    role: "Chasseur LinkedIn",
    description: "Prospecte sur LinkedIn et extrait des profils",
    mission: "Générer des leads B2B qualifiés via LinkedIn",
    model: "gemini-2.0-flash-exp",
    department: "prospection",
  },
  "cold-email-writer": {
    name: "Cold Email Writer",
    emoji: "✉️",
    role: "Rédacteur Emails Froids",
    description: "Rédige des emails de prospection personnalisés",
    mission: "Créer des emails qui convertissent",
    model: "claude-3-5-sonnet",
    department: "prospection",
  },
  "follow-up-bot": {
    name: "Follow-Up Bot",
    emoji: "🔄",
    role: "Bot de Relance",
    description: "Gère les relances automatiques des prospects",
    mission: "Maximiser le taux de réponse par relances intelligentes",
    model: "gpt-4o-mini",
    department: "prospection",
  },
  "crm-manager": {
    name: "CRM Manager",
    emoji: "📋",
    role: "Gestionnaire CRM",
    description: "Organise et enrichit la base de données prospects",
    mission: "Maintenir un CRM propre et actionnable",
    model: "llama-3.3-70b",
    department: "prospection",
  },
  "qualification-agent": {
    name: "Agent Qualification",
    emoji: "✅",
    role: "Qualificateur de Leads",
    description: "Score et qualifie les prospects selon des critères",
    mission: "Prioriser les meilleurs prospects",
    model: "gpt-4o-mini",
    department: "prospection",
  },
  "outreach-coordinator": {
    name: "Coordinateur Outreach",
    emoji: "📞",
    role: "Coordinateur de Prospection",
    description: "Orchestre les campagnes multi-canaux",
    mission: "Coordonner email, LinkedIn, phone pour maximum d'impact",
    model: "gemini-2.0-flash-exp",
    department: "prospection",
  },

  // Contenu (12 agents)
  "copywriter": {
    name: "Copywriter",
    emoji: "✍️",
    role: "Rédacteur Publicitaire",
    description: "Crée des textes persuasifs pour tous supports",
    mission: "Écrire des copies qui vendent",
    model: "claude-3-5-sonnet",
    department: "content",
  },
  "seo-specialist": {
    name: "Spécialiste SEO",
    emoji: "🔎",
    role: "Expert Référencement",
    description: "Optimise le contenu pour les moteurs de recherche",
    mission: "Améliorer le classement organique",
    model: "gpt-4",
    department: "content",
  },
  "blog-writer": {
    name: "Rédacteur Blog",
    emoji: "📝",
    role: "Auteur d'Articles",
    description: "Rédige des articles de blog engageants",
    mission: "Produire du contenu informatif et viral",
    model: "claude-3-5-sonnet",
    department: "content",
  },
  "social-media-writer": {
    name: "Rédacteur Social Media",
    emoji: "📱",
    role: "Créateur de Posts",
    description: "Crée des posts optimisés pour chaque plateforme",
    mission: "Générer de l'engagement sur les réseaux sociaux",
    model: "gpt-4o-mini",
    department: "content",
  },
  "video-scriptwriter": {
    name: "Scénariste Vidéo",
    emoji: "🎬",
    role: "Auteur de Scripts",
    description: "Écrit des scripts pour vidéos marketing",
    mission: "Créer des scripts captivants",
    model: "claude-3-5-sonnet",
    department: "content",
  },
  "email-marketer": {
    name: "Email Marketer",
    emoji: "💌",
    role: "Spécialiste Email",
    description: "Conçoit des campagnes email performantes",
    mission: "Maximiser l'open rate et les conversions email",
    model: "gpt-4",
    department: "content",
  },
  "landing-page-writer": {
    name: "Rédacteur Landing Page",
    emoji: "🎯",
    role: "Créateur de Pages",
    description: "Rédige des landing pages qui convertissent",
    mission: "Optimiser le taux de conversion",
    model: "claude-3-5-sonnet",
    department: "content",
  },
  "case-study-writer": {
    name: "Rédacteur Études de Cas",
    emoji: "📄",
    role: "Auteur de Success Stories",
    description: "Documente les réussites clients",
    mission: "Créer des preuves sociales convaincantes",
    model: "gpt-4",
    department: "content",
  },
  "press-release-writer": {
    name: "Rédacteur Communiqués",
    emoji: "📰",
    role: "Auteur de Presse",
    description: "Rédige des communiqués de presse professionnels",
    mission: "Obtenir de la couverture médiatique",
    model: "claude-3-5-sonnet",
    department: "content",
  },
  "ebook-creator": {
    name: "Créateur d'Ebooks",
    emoji: "📚",
    role: "Auteur de Guides",
    description: "Produit des ebooks et guides lead magnets",
    mission: "Créer du contenu premium pour générer des leads",
    model: "gpt-4",
    department: "content",
  },
  "infographic-designer": {
    name: "Designer Infographies",
    emoji: "📊",
    role: "Créateur Visuel",
    description: "Conçoit des infographies data-driven",
    mission: "Visualiser des données complexes simplement",
    model: "gemini-2.0-flash-exp",
    department: "content",
  },
  "podcast-scriptwriter": {
    name: "Scénariste Podcast",
    emoji: "🎙️",
    role: "Auteur Audio",
    description: "Écrit des scripts pour podcasts marketing",
    mission: "Créer du contenu audio engageant",
    model: "claude-3-5-sonnet",
    department: "content",
  },

  // Community (6 agents)
  "community-manager": {
    name: "Community Manager",
    emoji: "👥",
    role: "Gestionnaire de Communauté",
    description: "Anime et engage la communauté sur tous les canaux",
    mission: "Construire une communauté engagée",
    model: "gpt-4",
    department: "community",
  },
  "comment-responder": {
    name: "Répondeur Commentaires",
    emoji: "💬",
    role: "Gestionnaire de Réponses",
    description: "Répond aux commentaires sur les réseaux sociaux",
    mission: "Maintenir l'engagement et la satisfaction",
    model: "gpt-4o-mini",
    department: "community",
  },
  "dm-handler": {
    name: "Gestionnaire DM",
    emoji: "📩",
    role: "Agent Messages Privés",
    description: "Gère les messages privés et demandes",
    mission: "Convertir les DM en opportunités",
    model: "gpt-4o-mini",
    department: "community",
  },
  "review-manager": {
    name: "Gestionnaire d'Avis",
    emoji: "⭐",
    role: "Manager de Réputation",
    description: "Répond aux avis clients (Google, Facebook, etc.)",
    mission: "Protéger et améliorer la réputation en ligne",
    model: "claude-3-5-sonnet",
    department: "community",
  },
  "influencer-outreach": {
    name: "Outreach Influenceurs",
    emoji: "🌟",
    role: "Coordinateur Influenceurs",
    description: "Identifie et contacte des influenceurs pertinents",
    mission: "Créer des partenariats influenceurs",
    model: "gemini-2.0-flash-exp",
    department: "community",
  },
  "ugc-curator": {
    name: "Curateur UGC",
    emoji: "📸",
    role: "Gestionnaire Contenu Utilisateur",
    description: "Collecte et partage le contenu généré par les utilisateurs",
    mission: "Amplifier la voix des clients",
    model: "llama-3.3-70b",
    department: "community",
  },

  // Publicité (5 agents)
  "ads-strategist": {
    name: "Stratège Publicité",
    emoji: "🎯",
    role: "Planificateur de Campagnes",
    description: "Conçoit des stratégies publicitaires multi-plateformes",
    mission: "Maximiser le ROAS",
    model: "gpt-4",
    department: "advertising",
  },
  "facebook-ads-specialist": {
    name: "Spécialiste Facebook Ads",
    emoji: "📘",
    role: "Expert Meta Ads",
    description: "Crée et optimise des campagnes Facebook/Instagram",
    mission: "Générer des conversions à faible coût",
    model: "gemini-2.0-flash-exp",
    department: "advertising",
  },
  "google-ads-specialist": {
    name: "Spécialiste Google Ads",
    emoji: "🔍",
    role: "Expert Search Ads",
    description: "Gère les campagnes Google Ads (Search, Display, Shopping)",
    mission: "Capturer l'intention d'achat",
    model: "gpt-4",
    department: "advertising",
  },
  "ad-copywriter": {
    name: "Rédacteur Publicitaire",
    emoji: "✨",
    role: "Créateur d'Annonces",
    description: "Rédige des annonces publicitaires performantes",
    mission: "Créer des ads qui cliquent",
    model: "claude-3-5-sonnet",
    department: "advertising",
  },
  "retargeting-specialist": {
    name: "Spécialiste Retargeting",
    emoji: "🔄",
    role: "Expert Reciblage",
    description: "Configure des campagnes de retargeting intelligentes",
    mission: "Reconvertir les visiteurs perdus",
    model: "gemini-2.0-flash-exp",
    department: "advertising",
  },

  // Analytics (6 agents)
  "data-analyst": {
    name: "Analyste de Données",
    emoji: "📈",
    role: "Spécialiste Analytique",
    description: "Analyse les performances marketing et génère des insights",
    mission: "Transformer les données en décisions",
    model: "gpt-4",
    department: "analytics",
  },
  "ab-testing-specialist": {
    name: "Spécialiste A/B Testing",
    emoji: "🧪",
    role: "Expert Tests",
    description: "Conçoit et analyse des tests A/B",
    mission: "Optimiser par l'expérimentation",
    model: "gemini-2.0-flash-exp",
    department: "analytics",
  },
  "conversion-optimizer": {
    name: "Optimiseur de Conversion",
    emoji: "💹",
    role: "Expert CRO",
    description: "Identifie et corrige les frictions de conversion",
    mission: "Augmenter le taux de conversion",
    model: "gpt-4",
    department: "analytics",
  },
  "attribution-analyst": {
    name: "Analyste Attribution",
    emoji: "🎯",
    role: "Spécialiste Tracking",
    description: "Analyse les parcours clients et l'attribution",
    mission: "Comprendre ce qui génère vraiment des conversions",
    model: "claude-3-5-sonnet",
    department: "analytics",
  },
  "dashboard-creator": {
    name: "Créateur de Dashboards",
    emoji: "📊",
    role: "Designer de Rapports",
    description: "Crée des dashboards visuels et actionnables",
    mission: "Rendre les données accessibles",
    model: "gemini-2.0-flash-exp",
    department: "analytics",
  },
  "predictive-analyst": {
    name: "Analyste Prédictif",
    emoji: "🔮",
    role: "Expert Prévisions",
    description: "Utilise le ML pour prédire les tendances",
    mission: "Anticiper les opportunités et risques",
    model: "gpt-4",
    department: "analytics",
  },

  // Ops (4 agents)
  "automation-specialist": {
    name: "Spécialiste Automation",
    emoji: "⚙️",
    role: "Expert Automatisation",
    description: "Configure des workflows marketing automatisés",
    mission: "Automatiser les tâches répétitives",
    model: "gemini-2.0-flash-exp",
    department: "ops",
  },
  "integration-engineer": {
    name: "Ingénieur Intégrations",
    emoji: "🔗",
    role: "Connecteur de Systèmes",
    description: "Intègre les outils marketing entre eux",
    mission: "Créer un écosystème marketing fluide",
    model: "llama-3.3-70b",
    department: "ops",
  },
  "workflow-optimizer": {
    name: "Optimiseur de Workflows",
    emoji: "🔄",
    role: "Expert Processus",
    description: "Améliore l'efficacité des processus marketing",
    mission: "Éliminer les goulots d'étranglement",
    model: "gpt-4",
    department: "ops",
  },
  "tech-stack-manager": {
    name: "Gestionnaire Tech Stack",
    emoji: "🛠️",
    role: "Architecte Outils",
    description: "Sélectionne et gère les outils marketing",
    mission: "Optimiser la stack technologique",
    model: "claude-3-5-sonnet",
    department: "ops",
  },

  // Success (3 agents)
  "customer-success-agent": {
    name: "Agent Customer Success",
    emoji: "🤝",
    role: "Gestionnaire de Réussite",
    description: "Assure la satisfaction et la rétention clients",
    mission: "Maximiser la lifetime value",
    model: "gpt-4",
    department: "success",
  },
  "onboarding-specialist": {
    name: "Spécialiste Onboarding",
    emoji: "🚀",
    role: "Expert Intégration",
    description: "Guide les nouveaux clients vers le succès",
    mission: "Réduire le time-to-value",
    model: "claude-3-5-sonnet",
    department: "success",
  },
  "churn-prevention-agent": {
    name: "Agent Anti-Churn",
    emoji: "🛡️",
    role: "Protecteur de Rétention",
    description: "Identifie et prévient le churn",
    mission: "Retenir les clients à risque",
    model: "gpt-4",
    department: "success",
  },
};

export const DEPARTMENTS = [
  { id: "all", name: "Tous", count: 48 },
  { id: "direction", name: "Direction", count: 4 },
  { id: "prospection", name: "Prospection", count: 8 },
  { id: "content", name: "Contenu", count: 12 },
  { id: "community", name: "Community", count: 6 },
  { id: "advertising", name: "Publicité", count: 5 },
  { id: "analytics", name: "Analytics", count: 6 },
  { id: "ops", name: "Ops", count: 4 },
  { id: "success", name: "Success", count: 3 },
];
